# Site settings
title: wecode.io blog
email: hello@wecode.io
description: > # this means to ignore newlines until "baseurl:"
  Where wecoders come to share our thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wecode.io" # the base hostname & protocol for your site
twitter_username: wecodeio
github_username:  wecodeio

# Permalinks
permalink:        /:title/

# Build settings
markdown: kramdown

authors:
  wecode:
    name: We Code
    display_name: Staff
    web: http://www.wecode.io
    twitter: wecodeio
    github: wecodeio
  delucas:
    name: Lucas Videla
    display_name: Lucas
    web: http://delucas.github.io
    twitter: luke_ar
    github: delucas
  cristian:
    name: Cristian Rasch
    display_name: Cristian
    web: https://www.jaylen.com.ar
    twitter: cristianrasch
    github: cristianrasch

languages:
  english:
    display_name: en
    image: /images/flags/english.png
  spanish:
    display_name: sp
    image: /images/flags/spanish.png
